vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    mappings:
        poster_images:
            uri_prefix: /uploads/images/poster_images
            upload_destination: '%kernel.project_dir%/public/uploads/images/poster_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        figure_images:
            uri_prefix: /uploads/images/figure_images
            upload_destination: '%kernel.project_dir%/public/uploads/images/figure_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        staff_images:
            uri_prefix: /uploads/images/staff_images
            upload_destination: '%kernel.project_dir%/public/uploads/images/staff_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        cover_images:
            uri_prefix: /uploads/images/cover_images
            upload_destination: '%kernel.project_dir%/public/uploads/images/cover_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        thumbnails:
            uri_prefix: /uploads/images/thumbnails
            upload_destination: '%kernel.project_dir%/public/uploads/images/thumbnails'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
